Travis Build script
merchantprotocol/M1-warehouse-onestepcheckout-addon pull request #5
Opened 2017-01-14 14:14 UTC by alancarvalho

Issue #4.

2017-01-15 15:43 UTC, ghost approved these changes
Looks great

2017-01-16 18:25 UTC, jonathonbyrdziak approved these changes
We need to also install the checkout ext via this test sequence. but I'll get to that later.

2017-01-16 18:26 UTC, jonathonbyrdziak requested changes

2017-01-16 18:26 UTC, Jonathonbyrd commented on .travis.yml
> +  - sudo bash $MAGE_DIR/.modman/M1-travis-deployment-files/release.sh $MAGE_DIR $REPO_NAME
We need to disable the `release.sh` file for all ADDONS

2017-01-17 01:52 UTC, alancarvalho commented
Removed.

2017-01-17 03:09 UTC, jonathonbyrdziak approved these changes

2017-01-17 03:52 UTC, merged